### ISSUE TITLE
NPM audit issues

### ISSUE THREAD

**Issue by Luca-Terrazzan** [mcwhittemore/dyno-item-size#11]
Hello,

I am receiving auditing issues on this npm package that cannot be solved automatically. I think that updating dyno-item-size dependencies should be enough to solve this.

![image](https://user-images.githubusercontent.com/6852982/70901940-0982ad00-1ffc-11ea-9921-25b955d81c4a.png)

**Comment by Luca-Terrazzan** [comment]
I made a PR to solve this: #12

**Comment by eaviles** [comment]
@mcwhittemore Also having this issue :arrow_up:

**Comment by mcwhittemore** [comment]
Thanks. This has been merged and published as `v0.3.3`

**Comment by eaviles** [comment]
Thanks a lot @mcwhittemore! I appreciate the quick release
